// @generated by protoc-gen-es v2.2.3 with parameter "import_extension=ts,target=ts"
// @generated from file flow/legacy/entities/block_seal.proto (package entities, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/legacy/entities/block_seal.proto.
 */
export const file_flow_legacy_entities_block_seal: GenFile = /*@__PURE__*/
  fileDesc(
    "CiVmbG93L2xlZ2FjeS9lbnRpdGllcy9ibG9ja19zZWFsLnByb3RvEghlbnRpdGllcyKFAQoJQmxvY2tTZWFsEhAKCGJsb2NrX2lkGAEgASgMEhwKFGV4ZWN1dGlvbl9yZWNlaXB0X2lkGAIgASgMEiQKHGV4ZWN1dGlvbl9yZWNlaXB0X3NpZ25hdHVyZXMYAyADKAwSIgoacmVzdWx0X2FwcHJvdmFsX3NpZ25hdHVyZXMYBCADKAxCXgojb3JnLm9uZmxvdy5wcm90b2J1Zi5sZWdhY3kuZW50aXRpZXNaN2dpdGh1Yi5jb20vb25mbG93L2Zsb3cvcHJvdG9idWYvZ28vZmxvdy9sZWdhY3kvZW50aXRpZXNiBnByb3RvMw",
  )

/**
 * @generated from message entities.BlockSeal
 */
export type BlockSeal = Message<"entities.BlockSeal"> & {
  /**
   * @generated from field: bytes block_id = 1;
   */
  blockId: Uint8Array

  /**
   * @generated from field: bytes execution_receipt_id = 2;
   */
  executionReceiptId: Uint8Array

  /**
   * @generated from field: repeated bytes execution_receipt_signatures = 3;
   */
  executionReceiptSignatures: Uint8Array[]

  /**
   * @generated from field: repeated bytes result_approval_signatures = 4;
   */
  resultApprovalSignatures: Uint8Array[]
}

/**
 * Describes the message entities.BlockSeal.
 * Use `create(BlockSealSchema)` to create a new message.
 */
export const BlockSealSchema: GenMessage<BlockSeal> = /*@__PURE__*/
  messageDesc(file_flow_legacy_entities_block_seal, 0)
