// @generated by protoc-gen-es v2.2.3 with parameter "import_extension=ts,target=ts"
// @generated from file flow/legacy/entities/event.proto (package entities, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/legacy/entities/event.proto.
 */
export const file_flow_legacy_entities_event: GenFile = /*@__PURE__*/
  fileDesc(
    "CiBmbG93L2xlZ2FjeS9lbnRpdGllcy9ldmVudC5wcm90bxIIZW50aXRpZXMibgoFRXZlbnQSDAoEdHlwZRgBIAEoCRIWCg50cmFuc2FjdGlvbl9pZBgCIAEoDBIZChF0cmFuc2FjdGlvbl9pbmRleBgDIAEoDRITCgtldmVudF9pbmRleBgEIAEoDRIPCgdwYXlsb2FkGAUgASgMQl4KI29yZy5vbmZsb3cucHJvdG9idWYubGVnYWN5LmVudGl0aWVzWjdnaXRodWIuY29tL29uZmxvdy9mbG93L3Byb3RvYnVmL2dvL2Zsb3cvbGVnYWN5L2VudGl0aWVzYgZwcm90bzM",
  )

/**
 * @generated from message entities.Event
 */
export type Event = Message<"entities.Event"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string

  /**
   * @generated from field: bytes transaction_id = 2;
   */
  transactionId: Uint8Array

  /**
   * @generated from field: uint32 transaction_index = 3;
   */
  transactionIndex: number

  /**
   * @generated from field: uint32 event_index = 4;
   */
  eventIndex: number

  /**
   * @generated from field: bytes payload = 5;
   */
  payload: Uint8Array
}

/**
 * Describes the message entities.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_flow_legacy_entities_event, 0)
