// @generated by protoc-gen-es v2.2.3 with parameter "import_extension=ts,target=ts"
// @generated from file flow/legacy/entities/transaction.proto (package entities, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/legacy/entities/transaction.proto.
 */
export const file_flow_legacy_entities_transaction: GenFile = /*@__PURE__*/
  fileDesc(
    "CiZmbG93L2xlZ2FjeS9lbnRpdGllcy90cmFuc2FjdGlvbi5wcm90bxIIZW50aXRpZXMiwQMKC1RyYW5zYWN0aW9uEg4KBnNjcmlwdBgBIAEoDBIRCglhcmd1bWVudHMYAiADKAwSGgoScmVmZXJlbmNlX2Jsb2NrX2lkGAMgASgMEhEKCWdhc19saW1pdBgEIAEoBBI3Cgxwcm9wb3NhbF9rZXkYBSABKAsyIS5lbnRpdGllcy5UcmFuc2FjdGlvbi5Qcm9wb3NhbEtleRINCgVwYXllchgGIAEoDBITCgthdXRob3JpemVycxgHIAMoDBI7ChJwYXlsb2FkX3NpZ25hdHVyZXMYCCADKAsyHy5lbnRpdGllcy5UcmFuc2FjdGlvbi5TaWduYXR1cmUSPAoTZW52ZWxvcGVfc2lnbmF0dXJlcxgJIAMoCzIfLmVudGl0aWVzLlRyYW5zYWN0aW9uLlNpZ25hdHVyZRpHCgtQcm9wb3NhbEtleRIPCgdhZGRyZXNzGAEgASgMEg4KBmtleV9pZBgCIAEoDRIXCg9zZXF1ZW5jZV9udW1iZXIYAyABKAQaPwoJU2lnbmF0dXJlEg8KB2FkZHJlc3MYASABKAwSDgoGa2V5X2lkGAIgASgNEhEKCXNpZ25hdHVyZRgDIAEoDCpjChFUcmFuc2FjdGlvblN0YXR1cxILCgdVTktOT1dOEAASCwoHUEVORElORxABEg0KCUZJTkFMSVpFRBACEgwKCEVYRUNVVEVEEAMSCgoGU0VBTEVEEAQSCwoHRVhQSVJFRBAFQl4KI29yZy5vbmZsb3cucHJvdG9idWYubGVnYWN5LmVudGl0aWVzWjdnaXRodWIuY29tL29uZmxvdy9mbG93L3Byb3RvYnVmL2dvL2Zsb3cvbGVnYWN5L2VudGl0aWVzYgZwcm90bzM",
  )

/**
 * @generated from message entities.Transaction
 */
export type Transaction = Message<"entities.Transaction"> & {
  /**
   * @generated from field: bytes script = 1;
   */
  script: Uint8Array

  /**
   * @generated from field: repeated bytes arguments = 2;
   */
  arguments: Uint8Array[]

  /**
   * @generated from field: bytes reference_block_id = 3;
   */
  referenceBlockId: Uint8Array

  /**
   * @generated from field: uint64 gas_limit = 4;
   */
  gasLimit: bigint

  /**
   * @generated from field: entities.Transaction.ProposalKey proposal_key = 5;
   */
  proposalKey?: Transaction_ProposalKey

  /**
   * @generated from field: bytes payer = 6;
   */
  payer: Uint8Array

  /**
   * @generated from field: repeated bytes authorizers = 7;
   */
  authorizers: Uint8Array[]

  /**
   * @generated from field: repeated entities.Transaction.Signature payload_signatures = 8;
   */
  payloadSignatures: Transaction_Signature[]

  /**
   * @generated from field: repeated entities.Transaction.Signature envelope_signatures = 9;
   */
  envelopeSignatures: Transaction_Signature[]
}

/**
 * Describes the message entities.Transaction.
 * Use `create(TransactionSchema)` to create a new message.
 */
export const TransactionSchema: GenMessage<Transaction> = /*@__PURE__*/
  messageDesc(file_flow_legacy_entities_transaction, 0)

/**
 * @generated from message entities.Transaction.ProposalKey
 */
export type Transaction_ProposalKey =
  & Message<"entities.Transaction.ProposalKey">
  & {
    /**
     * @generated from field: bytes address = 1;
     */
    address: Uint8Array

    /**
     * @generated from field: uint32 key_id = 2;
     */
    keyId: number

    /**
     * @generated from field: uint64 sequence_number = 3;
     */
    sequenceNumber: bigint
  }

/**
 * Describes the message entities.Transaction.ProposalKey.
 * Use `create(Transaction_ProposalKeySchema)` to create a new message.
 */
export const Transaction_ProposalKeySchema: GenMessage<
  Transaction_ProposalKey
> = /*@__PURE__*/
  messageDesc(file_flow_legacy_entities_transaction, 0, 0)

/**
 * @generated from message entities.Transaction.Signature
 */
export type Transaction_Signature =
  & Message<"entities.Transaction.Signature">
  & {
    /**
     * @generated from field: bytes address = 1;
     */
    address: Uint8Array

    /**
     * @generated from field: uint32 key_id = 2;
     */
    keyId: number

    /**
     * @generated from field: bytes signature = 3;
     */
    signature: Uint8Array
  }

/**
 * Describes the message entities.Transaction.Signature.
 * Use `create(Transaction_SignatureSchema)` to create a new message.
 */
export const Transaction_SignatureSchema: GenMessage<
  Transaction_Signature
> = /*@__PURE__*/
  messageDesc(file_flow_legacy_entities_transaction, 0, 1)

/**
 * @generated from enum entities.TransactionStatus
 */
export enum TransactionStatus {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: FINALIZED = 2;
   */
  FINALIZED = 2,

  /**
   * @generated from enum value: EXECUTED = 3;
   */
  EXECUTED = 3,

  /**
   * @generated from enum value: SEALED = 4;
   */
  SEALED = 4,

  /**
   * @generated from enum value: EXPIRED = 5;
   */
  EXPIRED = 5,
}

/**
 * Describes the enum entities.TransactionStatus.
 */
export const TransactionStatusSchema: GenEnum<TransactionStatus> = /*@__PURE__*/
  enumDesc(file_flow_legacy_entities_transaction, 0)
