export const AUTH_REDIRECT_URL = '/dashboard/home'
export const AUTH_SIGN_IN_URL = '/auth/sign-in'
export const AUTH_SIGN_UP_URL = '/auth/sign-up'
export const PWORD_PLACEHOLDER = '***************'
export const URL_PLACEHOLDER = 'http://placeholder.com'
