// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file flow/entities/event.proto (package flow.entities, syntax proto3)

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/entities/event.proto.
 */
export const file_flow_entities_event: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChlmbG93L2VudGl0aWVzL2V2ZW50LnByb3RvEg1mbG93LmVudGl0aWVzIm4KBUV2ZW50EgwKBHR5cGUYASABKAkSFgoOdHJhbnNhY3Rpb25faWQYAiABKAwSGQoRdHJhbnNhY3Rpb25faW5kZXgYAyABKA0SEwoLZXZlbnRfaW5kZXgYBCABKA0SDwoHcGF5bG9hZBgFIAEoDCozChRFdmVudEVuY29kaW5nVmVyc2lvbhIPCgtKU09OX0NEQ19WMBAAEgoKBkNDRl9WMBABQlAKHG9yZy5vbmZsb3cucHJvdG9idWYuZW50aXRpZXNaMGdpdGh1Yi5jb20vb25mbG93L2Zsb3cvcHJvdG9idWYvZ28vZmxvdy9lbnRpdGllc2IGcHJvdG8z",
  )

/**
 * @generated from message flow.entities.Event
 */
export type Event = Message<"flow.entities.Event"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string

  /**
   * @generated from field: bytes transaction_id = 2;
   */
  transactionId: Uint8Array

  /**
   * @generated from field: uint32 transaction_index = 3;
   */
  transactionIndex: number

  /**
   * @generated from field: uint32 event_index = 4;
   */
  eventIndex: number

  /**
   * @generated from field: bytes payload = 5;
   */
  payload: Uint8Array
}

/**
 * Describes the message flow.entities.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> =
  /*@__PURE__*/
  messageDesc(file_flow_entities_event, 0)

/**
 * @generated from enum flow.entities.EventEncodingVersion
 */
export enum EventEncodingVersion {
  /**
   * @generated from enum value: JSON_CDC_V0 = 0;
   */
  JSON_CDC_V0 = 0,

  /**
   * @generated from enum value: CCF_V0 = 1;
   */
  CCF_V0 = 1,
}

/**
 * Describes the enum flow.entities.EventEncodingVersion.
 */
export const EventEncodingVersionSchema: GenEnum<EventEncodingVersion> =
  /*@__PURE__*/
  enumDesc(file_flow_entities_event, 0)
