// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file flow/entities/register.proto (package flow.entities, syntax proto3)

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/entities/register.proto.
 */
export const file_flow_entities_register: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChxmbG93L2VudGl0aWVzL3JlZ2lzdGVyLnByb3RvEg1mbG93LmVudGl0aWVzIigKClJlZ2lzdGVySUQSDQoFb3duZXIYASABKAwSCwoDa2V5GAIgASgMQlAKHG9yZy5vbmZsb3cucHJvdG9idWYuZW50aXRpZXNaMGdpdGh1Yi5jb20vb25mbG93L2Zsb3cvcHJvdG9idWYvZ28vZmxvdy9lbnRpdGllc2IGcHJvdG8z",
  )

/**
 * @generated from message flow.entities.RegisterID
 */
export type RegisterID = Message<"flow.entities.RegisterID"> & {
  /**
   * @generated from field: bytes owner = 1;
   */
  owner: Uint8Array

  /**
   * @generated from field: bytes key = 2;
   */
  key: Uint8Array
}

/**
 * Describes the message flow.entities.RegisterID.
 * Use `create(RegisterIDSchema)` to create a new message.
 */
export const RegisterIDSchema: GenMessage<RegisterID> =
  /*@__PURE__*/
  messageDesc(file_flow_entities_register, 0)
