// @generated by protoc-gen-es v2.2.3 with parameter "import_extension=ts,target=ts"
// @generated from file flow/entities/account.proto (package flow.entities, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/entities/account.proto.
 */
export const file_flow_entities_account: GenFile = /*@__PURE__*/
  fileDesc(
    "ChtmbG93L2VudGl0aWVzL2FjY291bnQucHJvdG8SDWZsb3cuZW50aXRpZXMizgEKB0FjY291bnQSDwoHYWRkcmVzcxgBIAEoDBIPCgdiYWxhbmNlGAIgASgEEgwKBGNvZGUYAyABKAwSJwoEa2V5cxgEIAMoCzIZLmZsb3cuZW50aXRpZXMuQWNjb3VudEtleRI4Cgljb250cmFjdHMYBSADKAsyJS5mbG93LmVudGl0aWVzLkFjY291bnQuQ29udHJhY3RzRW50cnkaMAoOQ29udHJhY3RzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgMOgI4ASKPAQoKQWNjb3VudEtleRINCgVpbmRleBgBIAEoDRISCgpwdWJsaWNfa2V5GAIgASgMEhEKCXNpZ25fYWxnbxgDIAEoDRIRCgloYXNoX2FsZ28YBCABKA0SDgoGd2VpZ2h0GAUgASgNEhcKD3NlcXVlbmNlX251bWJlchgGIAEoDRIPCgdyZXZva2VkGAcgASgIQlAKHG9yZy5vbmZsb3cucHJvdG9idWYuZW50aXRpZXNaMGdpdGh1Yi5jb20vb25mbG93L2Zsb3cvcHJvdG9idWYvZ28vZmxvdy9lbnRpdGllc2IGcHJvdG8z",
  )

/**
 * @generated from message flow.entities.Account
 */
export type Account = Message<"flow.entities.Account"> & {
  /**
   * @generated from field: bytes address = 1;
   */
  address: Uint8Array

  /**
   * @generated from field: uint64 balance = 2;
   */
  balance: bigint

  /**
   * @generated from field: bytes code = 3;
   */
  code: Uint8Array

  /**
   * @generated from field: repeated flow.entities.AccountKey keys = 4;
   */
  keys: AccountKey[]

  /**
   * @generated from field: map<string, bytes> contracts = 5;
   */
  contracts: { [key: string]: Uint8Array }
}

/**
 * Describes the message flow.entities.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema: GenMessage<Account> = /*@__PURE__*/
  messageDesc(file_flow_entities_account, 0)

/**
 * @generated from message flow.entities.AccountKey
 */
export type AccountKey = Message<"flow.entities.AccountKey"> & {
  /**
   * @generated from field: uint32 index = 1;
   */
  index: number

  /**
   * @generated from field: bytes public_key = 2;
   */
  publicKey: Uint8Array

  /**
   * @generated from field: uint32 sign_algo = 3;
   */
  signAlgo: number

  /**
   * @generated from field: uint32 hash_algo = 4;
   */
  hashAlgo: number

  /**
   * @generated from field: uint32 weight = 5;
   */
  weight: number

  /**
   * @generated from field: uint32 sequence_number = 6;
   */
  sequenceNumber: number

  /**
   * @generated from field: bool revoked = 7;
   */
  revoked: boolean
}

/**
 * Describes the message flow.entities.AccountKey.
 * Use `create(AccountKeySchema)` to create a new message.
 */
export const AccountKeySchema: GenMessage<AccountKey> = /*@__PURE__*/
  messageDesc(file_flow_entities_account, 1)
