// @generated by protoc-gen-es v2.2.3 with parameter "import_extension=ts,target=ts"
// @generated from file flow/entities/block_seal.proto (package flow.entities, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/entities/block_seal.proto.
 */
export const file_flow_entities_block_seal: GenFile = /*@__PURE__*/
  fileDesc(
    "Ch5mbG93L2VudGl0aWVzL2Jsb2NrX3NlYWwucHJvdG8SDWZsb3cuZW50aXRpZXMi8wEKCUJsb2NrU2VhbBIQCghibG9ja19pZBgBIAEoDBIcChRleGVjdXRpb25fcmVjZWlwdF9pZBgCIAEoDBIkChxleGVjdXRpb25fcmVjZWlwdF9zaWduYXR1cmVzGAMgAygMEiIKGnJlc3VsdF9hcHByb3ZhbF9zaWduYXR1cmVzGAQgAygMEhMKC2ZpbmFsX3N0YXRlGAUgASgMEhEKCXJlc3VsdF9pZBgGIAEoDBJEChhhZ2dyZWdhdGVkX2FwcHJvdmFsX3NpZ3MYByADKAsyIi5mbG93LmVudGl0aWVzLkFnZ3JlZ2F0ZWRTaWduYXR1cmUiRgoTQWdncmVnYXRlZFNpZ25hdHVyZRIbChN2ZXJpZmllcl9zaWduYXR1cmVzGAEgAygMEhIKCnNpZ25lcl9pZHMYAiADKAxCUAocb3JnLm9uZmxvdy5wcm90b2J1Zi5lbnRpdGllc1owZ2l0aHViLmNvbS9vbmZsb3cvZmxvdy9wcm90b2J1Zi9nby9mbG93L2VudGl0aWVzYgZwcm90bzM",
  )

/**
 * @generated from message flow.entities.BlockSeal
 */
export type BlockSeal = Message<"flow.entities.BlockSeal"> & {
  /**
   * @generated from field: bytes block_id = 1;
   */
  blockId: Uint8Array

  /**
   * @generated from field: bytes execution_receipt_id = 2;
   */
  executionReceiptId: Uint8Array

  /**
   * @generated from field: repeated bytes execution_receipt_signatures = 3;
   */
  executionReceiptSignatures: Uint8Array[]

  /**
   * @generated from field: repeated bytes result_approval_signatures = 4;
   */
  resultApprovalSignatures: Uint8Array[]

  /**
   * @generated from field: bytes final_state = 5;
   */
  finalState: Uint8Array

  /**
   * @generated from field: bytes result_id = 6;
   */
  resultId: Uint8Array

  /**
   * @generated from field: repeated flow.entities.AggregatedSignature aggregated_approval_sigs = 7;
   */
  aggregatedApprovalSigs: AggregatedSignature[]
}

/**
 * Describes the message flow.entities.BlockSeal.
 * Use `create(BlockSealSchema)` to create a new message.
 */
export const BlockSealSchema: GenMessage<BlockSeal> = /*@__PURE__*/
  messageDesc(file_flow_entities_block_seal, 0)

/**
 * @generated from message flow.entities.AggregatedSignature
 */
export type AggregatedSignature =
  & Message<"flow.entities.AggregatedSignature">
  & {
    /**
     * @generated from field: repeated bytes verifier_signatures = 1;
     */
    verifierSignatures: Uint8Array[]

    /**
     * @generated from field: repeated bytes signer_ids = 2;
     */
    signerIds: Uint8Array[]
  }

/**
 * Describes the message flow.entities.AggregatedSignature.
 * Use `create(AggregatedSignatureSchema)` to create a new message.
 */
export const AggregatedSignatureSchema: GenMessage<
  AggregatedSignature
> = /*@__PURE__*/
  messageDesc(file_flow_entities_block_seal, 1)
