// @generated by protoc-gen-es v2.2.3 with parameter "import_extension=ts,target=ts"
// @generated from file flow/entities/block.proto (package flow.entities, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Timestamp } from "@bufbuild/protobuf/wkt"
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt"
import type { CollectionGuarantee } from "./collection_pb.ts"
import { file_flow_entities_collection } from "./collection_pb.ts"
import type { BlockSeal } from "./block_seal_pb.ts"
import { file_flow_entities_block_seal } from "./block_seal_pb.ts"
import type {
  ExecutionReceiptMeta,
  ExecutionResult,
} from "./execution_result_pb.ts"
import { file_flow_entities_execution_result } from "./execution_result_pb.ts"
import type { BlockHeader } from "./block_header_pb.ts"
import { file_flow_entities_block_header } from "./block_header_pb.ts"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/entities/block.proto.
 */
export const file_flow_entities_block: GenFile = /*@__PURE__*/
  fileDesc(
    "ChlmbG93L2VudGl0aWVzL2Jsb2NrLnByb3RvEg1mbG93LmVudGl0aWVzIsADCgVCbG9jaxIKCgJpZBgBIAEoDBIRCglwYXJlbnRfaWQYAiABKAwSDgoGaGVpZ2h0GAMgASgEEi0KCXRpbWVzdGFtcBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASQQoVY29sbGVjdGlvbl9ndWFyYW50ZWVzGAUgAygLMiIuZmxvdy5lbnRpdGllcy5Db2xsZWN0aW9uR3VhcmFudGVlEi0KC2Jsb2NrX3NlYWxzGAYgAygLMhguZmxvdy5lbnRpdGllcy5CbG9ja1NlYWwSEgoKc2lnbmF0dXJlcxgHIAMoDBJHChpleGVjdXRpb25fcmVjZWlwdF9tZXRhTGlzdBgIIAMoCzIjLmZsb3cuZW50aXRpZXMuRXhlY3V0aW9uUmVjZWlwdE1ldGESPQoVZXhlY3V0aW9uX3Jlc3VsdF9saXN0GAkgAygLMh4uZmxvdy5lbnRpdGllcy5FeGVjdXRpb25SZXN1bHQSMAoMYmxvY2tfaGVhZGVyGAogASgLMhouZmxvdy5lbnRpdGllcy5CbG9ja0hlYWRlchIZChFwcm90b2NvbF9zdGF0ZV9pZBgLIAEoDCpHCgtCbG9ja1N0YXR1cxIRCg1CTE9DS19VTktOT1dOEAASEwoPQkxPQ0tfRklOQUxJWkVEEAESEAoMQkxPQ0tfU0VBTEVEEAJCUAocb3JnLm9uZmxvdy5wcm90b2J1Zi5lbnRpdGllc1owZ2l0aHViLmNvbS9vbmZsb3cvZmxvdy9wcm90b2J1Zi9nby9mbG93L2VudGl0aWVzYgZwcm90bzM",
    [
      file_google_protobuf_timestamp,
      file_flow_entities_collection,
      file_flow_entities_block_seal,
      file_flow_entities_execution_result,
      file_flow_entities_block_header,
    ],
  )

/**
 * @generated from message flow.entities.Block
 */
export type Block = Message<"flow.entities.Block"> & {
  /**
   * @generated from field: bytes id = 1;
   */
  id: Uint8Array

  /**
   * @generated from field: bytes parent_id = 2;
   */
  parentId: Uint8Array

  /**
   * @generated from field: uint64 height = 3;
   */
  height: bigint

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp

  /**
   * @generated from field: repeated flow.entities.CollectionGuarantee collection_guarantees = 5;
   */
  collectionGuarantees: CollectionGuarantee[]

  /**
   * @generated from field: repeated flow.entities.BlockSeal block_seals = 6;
   */
  blockSeals: BlockSeal[]

  /**
   * @generated from field: repeated bytes signatures = 7;
   */
  signatures: Uint8Array[]

  /**
   * @generated from field: repeated flow.entities.ExecutionReceiptMeta execution_receipt_metaList = 8;
   */
  executionReceiptMetaList: ExecutionReceiptMeta[]

  /**
   * @generated from field: repeated flow.entities.ExecutionResult execution_result_list = 9;
   */
  executionResultList: ExecutionResult[]

  /**
   * @generated from field: flow.entities.BlockHeader block_header = 10;
   */
  blockHeader?: BlockHeader

  /**
   * @generated from field: bytes protocol_state_id = 11;
   */
  protocolStateId: Uint8Array
}

/**
 * Describes the message flow.entities.Block.
 * Use `create(BlockSchema)` to create a new message.
 */
export const BlockSchema: GenMessage<Block> = /*@__PURE__*/
  messageDesc(file_flow_entities_block, 0)

/**
 * @generated from enum flow.entities.BlockStatus
 */
export enum BlockStatus {
  /**
   * @generated from enum value: BLOCK_UNKNOWN = 0;
   */
  BLOCK_UNKNOWN = 0,

  /**
   * @generated from enum value: BLOCK_FINALIZED = 1;
   */
  BLOCK_FINALIZED = 1,

  /**
   * @generated from enum value: BLOCK_SEALED = 2;
   */
  BLOCK_SEALED = 2,
}

/**
 * Describes the enum flow.entities.BlockStatus.
 */
export const BlockStatusSchema: GenEnum<BlockStatus> = /*@__PURE__*/
  enumDesc(file_flow_entities_block, 0)
