// @generated by protoc-gen-es v2.2.3 with parameter "import_extension=ts,target=ts"
// @generated from file flow/entities/collection.proto (package flow.entities, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/entities/collection.proto.
 */
export const file_flow_entities_collection: GenFile = /*@__PURE__*/
  fileDesc(
    "Ch5mbG93L2VudGl0aWVzL2NvbGxlY3Rpb24ucHJvdG8SDWZsb3cuZW50aXRpZXMiMQoKQ29sbGVjdGlvbhIKCgJpZBgBIAEoDBIXCg90cmFuc2FjdGlvbl9pZHMYAiADKAwimwEKE0NvbGxlY3Rpb25HdWFyYW50ZWUSFQoNY29sbGVjdGlvbl9pZBgBIAEoDBISCgpzaWduYXR1cmVzGAIgAygMEhoKEnJlZmVyZW5jZV9ibG9ja19pZBgDIAEoDBIRCglzaWduYXR1cmUYBCABKAwSEgoKc2lnbmVyX2lkcxgFIAMoDBIWCg5zaWduZXJfaW5kaWNlcxgGIAEoDEJQChxvcmcub25mbG93LnByb3RvYnVmLmVudGl0aWVzWjBnaXRodWIuY29tL29uZmxvdy9mbG93L3Byb3RvYnVmL2dvL2Zsb3cvZW50aXRpZXNiBnByb3RvMw",
  )

/**
 * @generated from message flow.entities.Collection
 */
export type Collection = Message<"flow.entities.Collection"> & {
  /**
   * @generated from field: bytes id = 1;
   */
  id: Uint8Array

  /**
   * @generated from field: repeated bytes transaction_ids = 2;
   */
  transactionIds: Uint8Array[]
}

/**
 * Describes the message flow.entities.Collection.
 * Use `create(CollectionSchema)` to create a new message.
 */
export const CollectionSchema: GenMessage<Collection> = /*@__PURE__*/
  messageDesc(file_flow_entities_collection, 0)

/**
 * @generated from message flow.entities.CollectionGuarantee
 */
export type CollectionGuarantee =
  & Message<"flow.entities.CollectionGuarantee">
  & {
    /**
     * @generated from field: bytes collection_id = 1;
     */
    collectionId: Uint8Array

    /**
     * @generated from field: repeated bytes signatures = 2;
     */
    signatures: Uint8Array[]

    /**
     * @generated from field: bytes reference_block_id = 3;
     */
    referenceBlockId: Uint8Array

    /**
     * @generated from field: bytes signature = 4;
     */
    signature: Uint8Array

    /**
     * deprecated!! value will be empty. replaced by signer_indices
     *
     * @generated from field: repeated bytes signer_ids = 5;
     */
    signerIds: Uint8Array[]

    /**
     * @generated from field: bytes signer_indices = 6;
     */
    signerIndices: Uint8Array
  }

/**
 * Describes the message flow.entities.CollectionGuarantee.
 * Use `create(CollectionGuaranteeSchema)` to create a new message.
 */
export const CollectionGuaranteeSchema: GenMessage<
  CollectionGuarantee
> = /*@__PURE__*/
  messageDesc(file_flow_entities_collection, 1)
