// @generated by protoc-gen-es v2.2.3 with parameter "import_extension=ts,target=ts"
// @generated from file flow/entities/metadata.proto (package flow.entities, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/entities/metadata.proto.
 */
export const file_flow_entities_metadata: GenFile = /*@__PURE__*/
  fileDesc(
    "ChxmbG93L2VudGl0aWVzL21ldGFkYXRhLnByb3RvEg1mbG93LmVudGl0aWVzIn8KCE1ldGFkYXRhEiEKGWxhdGVzdF9maW5hbGl6ZWRfYmxvY2tfaWQYASABKAwSHwoXbGF0ZXN0X2ZpbmFsaXplZF9oZWlnaHQYAiABKAQSDwoHbm9kZV9pZBgDIAEoDBIeChZoaWdoZXN0X2luZGV4ZWRfaGVpZ2h0GAQgASgEQlAKHG9yZy5vbmZsb3cucHJvdG9idWYuZW50aXRpZXNaMGdpdGh1Yi5jb20vb25mbG93L2Zsb3cvcHJvdG9idWYvZ28vZmxvdy9lbnRpdGllc2IGcHJvdG8z",
  )

/**
 * @generated from message flow.entities.Metadata
 */
export type Metadata = Message<"flow.entities.Metadata"> & {
  /**
   * @generated from field: bytes latest_finalized_block_id = 1;
   */
  latestFinalizedBlockId: Uint8Array

  /**
   * @generated from field: uint64 latest_finalized_height = 2;
   */
  latestFinalizedHeight: bigint

  /**
   * @generated from field: bytes node_id = 3;
   */
  nodeId: Uint8Array

  /**
   * @generated from field: uint64 highest_indexed_height = 4;
   */
  highestIndexedHeight: bigint
}

/**
 * Describes the message flow.entities.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_flow_entities_metadata, 0)
