// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file flow/legacy/entities/block_header.proto (package entities, syntax proto3)

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1"
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1"
import type { Timestamp } from "@bufbuild/protobuf/wkt"
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/legacy/entities/block_header.proto.
 */
export const file_flow_legacy_entities_block_header: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CidmbG93L2xlZ2FjeS9lbnRpdGllcy9ibG9ja19oZWFkZXIucHJvdG8SCGVudGl0aWVzImsKC0Jsb2NrSGVhZGVyEgoKAmlkGAEgASgMEhEKCXBhcmVudF9pZBgCIAEoDBIOCgZoZWlnaHQYAyABKAQSLQoJdGltZXN0YW1wGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEJeCiNvcmcub25mbG93LnByb3RvYnVmLmxlZ2FjeS5lbnRpdGllc1o3Z2l0aHViLmNvbS9vbmZsb3cvZmxvdy9wcm90b2J1Zi9nby9mbG93L2xlZ2FjeS9lbnRpdGllc2IGcHJvdG8z",
    [file_google_protobuf_timestamp],
  )

/**
 * @generated from message entities.BlockHeader
 */
export type BlockHeader = Message<"entities.BlockHeader"> & {
  /**
   * @generated from field: bytes id = 1;
   */
  id: Uint8Array

  /**
   * @generated from field: bytes parent_id = 2;
   */
  parentId: Uint8Array

  /**
   * @generated from field: uint64 height = 3;
   */
  height: bigint

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp
}

/**
 * Describes the message entities.BlockHeader.
 * Use `create(BlockHeaderSchema)` to create a new message.
 */
export const BlockHeaderSchema: GenMessage<BlockHeader> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_entities_block_header, 0)
