// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file flow/legacy/execution/execution.proto (package execution, syntax proto3)

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv1"
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv1"
import type { Account } from "../entities/account_pb"
import { file_flow_legacy_entities_account } from "../entities/account_pb"
import type { Event } from "../entities/event_pb"
import { file_flow_legacy_entities_event } from "../entities/event_pb"
import type { Message } from "@bufbuild/protobuf"

/**
 * Describes the file flow/legacy/execution/execution.proto.
 */
export const file_flow_legacy_execution_execution: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CiVmbG93L2xlZ2FjeS9leGVjdXRpb24vZXhlY3V0aW9uLnByb3RvEglleGVjdXRpb24iDQoLUGluZ1JlcXVlc3QiDgoMUGluZ1Jlc3BvbnNlIj8KGkdldEFjY291bnRBdEJsb2NrSURSZXF1ZXN0EhAKCGJsb2NrX2lkGAEgASgMEg8KB2FkZHJlc3MYAiABKAwiQQobR2V0QWNjb3VudEF0QmxvY2tJRFJlc3BvbnNlEiIKB2FjY291bnQYASABKAsyES5lbnRpdGllcy5BY2NvdW50IlQKHUV4ZWN1dGVTY3JpcHRBdEJsb2NrSURSZXF1ZXN0EhAKCGJsb2NrX2lkGAEgASgMEg4KBnNjcmlwdBgCIAEoDBIRCglhcmd1bWVudHMYAyADKAwiLwoeRXhlY3V0ZVNjcmlwdEF0QmxvY2tJRFJlc3BvbnNlEg0KBXZhbHVlGAEgASgMIrIBChxHZXRFdmVudHNGb3JCbG9ja0lEc1Jlc3BvbnNlEj8KB3Jlc3VsdHMYASADKAsyLi5leGVjdXRpb24uR2V0RXZlbnRzRm9yQmxvY2tJRHNSZXNwb25zZS5SZXN1bHQaUQoGUmVzdWx0EhAKCGJsb2NrX2lkGAEgASgMEhQKDGJsb2NrX2hlaWdodBgCIAEoBBIfCgZldmVudHMYAyADKAsyDy5lbnRpdGllcy5FdmVudCI+ChtHZXRFdmVudHNGb3JCbG9ja0lEc1JlcXVlc3QSDAoEdHlwZRgBIAEoCRIRCglibG9ja19pZHMYAiADKAwiRwobR2V0VHJhbnNhY3Rpb25SZXN1bHRSZXF1ZXN0EhAKCGJsb2NrX2lkGAEgASgMEhYKDnRyYW5zYWN0aW9uX2lkGAIgASgMImsKHEdldFRyYW5zYWN0aW9uUmVzdWx0UmVzcG9uc2USEwoLc3RhdHVzX2NvZGUYASABKA0SFQoNZXJyb3JfbWVzc2FnZRgCIAEoCRIfCgZldmVudHMYAyADKAsyDy5lbnRpdGllcy5FdmVudDLuAwoMRXhlY3V0aW9uQVBJEjcKBFBpbmcSFi5leGVjdXRpb24uUGluZ1JlcXVlc3QaFy5leGVjdXRpb24uUGluZ1Jlc3BvbnNlEmQKE0dldEFjY291bnRBdEJsb2NrSUQSJS5leGVjdXRpb24uR2V0QWNjb3VudEF0QmxvY2tJRFJlcXVlc3QaJi5leGVjdXRpb24uR2V0QWNjb3VudEF0QmxvY2tJRFJlc3BvbnNlEm0KFkV4ZWN1dGVTY3JpcHRBdEJsb2NrSUQSKC5leGVjdXRpb24uRXhlY3V0ZVNjcmlwdEF0QmxvY2tJRFJlcXVlc3QaKS5leGVjdXRpb24uRXhlY3V0ZVNjcmlwdEF0QmxvY2tJRFJlc3BvbnNlEmcKFEdldEV2ZW50c0ZvckJsb2NrSURzEiYuZXhlY3V0aW9uLkdldEV2ZW50c0ZvckJsb2NrSURzUmVxdWVzdBonLmV4ZWN1dGlvbi5HZXRFdmVudHNGb3JCbG9ja0lEc1Jlc3BvbnNlEmcKFEdldFRyYW5zYWN0aW9uUmVzdWx0EiYuZXhlY3V0aW9uLkdldFRyYW5zYWN0aW9uUmVzdWx0UmVxdWVzdBonLmV4ZWN1dGlvbi5HZXRUcmFuc2FjdGlvblJlc3VsdFJlc3BvbnNlQmAKJG9yZy5vbmZsb3cucHJvdG9idWYubGVnYWN5LmV4ZWN1dGlvblo4Z2l0aHViLmNvbS9vbmZsb3cvZmxvdy9wcm90b2J1Zi9nby9mbG93L2xlZ2FjeS9leGVjdXRpb25iBnByb3RvMw",
    [file_flow_legacy_entities_account, file_flow_legacy_entities_event],
  )

/**
 * @generated from message execution.PingRequest
 */
export type PingRequest = Message<"execution.PingRequest"> & {}

/**
 * Describes the message execution.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 0)

/**
 * @generated from message execution.PingResponse
 */
export type PingResponse = Message<"execution.PingResponse"> & {}

/**
 * Describes the message execution.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 1)

/**
 * @generated from message execution.GetAccountAtBlockIDRequest
 */
export type GetAccountAtBlockIDRequest =
  Message<"execution.GetAccountAtBlockIDRequest"> & {
    /**
     * @generated from field: bytes block_id = 1;
     */
    blockId: Uint8Array

    /**
     * @generated from field: bytes address = 2;
     */
    address: Uint8Array
  }

/**
 * Describes the message execution.GetAccountAtBlockIDRequest.
 * Use `create(GetAccountAtBlockIDRequestSchema)` to create a new message.
 */
export const GetAccountAtBlockIDRequestSchema: GenMessage<GetAccountAtBlockIDRequest> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 2)

/**
 * @generated from message execution.GetAccountAtBlockIDResponse
 */
export type GetAccountAtBlockIDResponse =
  Message<"execution.GetAccountAtBlockIDResponse"> & {
    /**
     * @generated from field: entities.Account account = 1;
     */
    account?: Account
  }

/**
 * Describes the message execution.GetAccountAtBlockIDResponse.
 * Use `create(GetAccountAtBlockIDResponseSchema)` to create a new message.
 */
export const GetAccountAtBlockIDResponseSchema: GenMessage<GetAccountAtBlockIDResponse> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 3)

/**
 * @generated from message execution.ExecuteScriptAtBlockIDRequest
 */
export type ExecuteScriptAtBlockIDRequest =
  Message<"execution.ExecuteScriptAtBlockIDRequest"> & {
    /**
     * @generated from field: bytes block_id = 1;
     */
    blockId: Uint8Array

    /**
     * @generated from field: bytes script = 2;
     */
    script: Uint8Array

    /**
     * @generated from field: repeated bytes arguments = 3;
     */
    arguments: Uint8Array[]
  }

/**
 * Describes the message execution.ExecuteScriptAtBlockIDRequest.
 * Use `create(ExecuteScriptAtBlockIDRequestSchema)` to create a new message.
 */
export const ExecuteScriptAtBlockIDRequestSchema: GenMessage<ExecuteScriptAtBlockIDRequest> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 4)

/**
 * @generated from message execution.ExecuteScriptAtBlockIDResponse
 */
export type ExecuteScriptAtBlockIDResponse =
  Message<"execution.ExecuteScriptAtBlockIDResponse"> & {
    /**
     * @generated from field: bytes value = 1;
     */
    value: Uint8Array
  }

/**
 * Describes the message execution.ExecuteScriptAtBlockIDResponse.
 * Use `create(ExecuteScriptAtBlockIDResponseSchema)` to create a new message.
 */
export const ExecuteScriptAtBlockIDResponseSchema: GenMessage<ExecuteScriptAtBlockIDResponse> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 5)

/**
 * @generated from message execution.GetEventsForBlockIDsResponse
 */
export type GetEventsForBlockIDsResponse =
  Message<"execution.GetEventsForBlockIDsResponse"> & {
    /**
     * @generated from field: repeated execution.GetEventsForBlockIDsResponse.Result results = 1;
     */
    results: GetEventsForBlockIDsResponse_Result[]
  }

/**
 * Describes the message execution.GetEventsForBlockIDsResponse.
 * Use `create(GetEventsForBlockIDsResponseSchema)` to create a new message.
 */
export const GetEventsForBlockIDsResponseSchema: GenMessage<GetEventsForBlockIDsResponse> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 6)

/**
 * @generated from message execution.GetEventsForBlockIDsResponse.Result
 */
export type GetEventsForBlockIDsResponse_Result =
  Message<"execution.GetEventsForBlockIDsResponse.Result"> & {
    /**
     * @generated from field: bytes block_id = 1;
     */
    blockId: Uint8Array

    /**
     * @generated from field: uint64 block_height = 2;
     */
    blockHeight: bigint

    /**
     * @generated from field: repeated entities.Event events = 3;
     */
    events: Event[]
  }

/**
 * Describes the message execution.GetEventsForBlockIDsResponse.Result.
 * Use `create(GetEventsForBlockIDsResponse_ResultSchema)` to create a new message.
 */
export const GetEventsForBlockIDsResponse_ResultSchema: GenMessage<GetEventsForBlockIDsResponse_Result> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 6, 0)

/**
 * @generated from message execution.GetEventsForBlockIDsRequest
 */
export type GetEventsForBlockIDsRequest =
  Message<"execution.GetEventsForBlockIDsRequest"> & {
    /**
     * @generated from field: string type = 1;
     */
    type: string

    /**
     * @generated from field: repeated bytes block_ids = 2;
     */
    blockIds: Uint8Array[]
  }

/**
 * Describes the message execution.GetEventsForBlockIDsRequest.
 * Use `create(GetEventsForBlockIDsRequestSchema)` to create a new message.
 */
export const GetEventsForBlockIDsRequestSchema: GenMessage<GetEventsForBlockIDsRequest> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 7)

/**
 * @generated from message execution.GetTransactionResultRequest
 */
export type GetTransactionResultRequest =
  Message<"execution.GetTransactionResultRequest"> & {
    /**
     * @generated from field: bytes block_id = 1;
     */
    blockId: Uint8Array

    /**
     * @generated from field: bytes transaction_id = 2;
     */
    transactionId: Uint8Array
  }

/**
 * Describes the message execution.GetTransactionResultRequest.
 * Use `create(GetTransactionResultRequestSchema)` to create a new message.
 */
export const GetTransactionResultRequestSchema: GenMessage<GetTransactionResultRequest> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 8)

/**
 * @generated from message execution.GetTransactionResultResponse
 */
export type GetTransactionResultResponse =
  Message<"execution.GetTransactionResultResponse"> & {
    /**
     * @generated from field: uint32 status_code = 1;
     */
    statusCode: number

    /**
     * @generated from field: string error_message = 2;
     */
    errorMessage: string

    /**
     * @generated from field: repeated entities.Event events = 3;
     */
    events: Event[]
  }

/**
 * Describes the message execution.GetTransactionResultResponse.
 * Use `create(GetTransactionResultResponseSchema)` to create a new message.
 */
export const GetTransactionResultResponseSchema: GenMessage<GetTransactionResultResponse> =
  /*@__PURE__*/
  messageDesc(file_flow_legacy_execution_execution, 9)

/**
 * ExecutionAPI is the API provided by the execution nodes.
 *
 * @generated from service execution.ExecutionAPI
 */
export const ExecutionAPI: GenService<{
  /**
   * Ping is used to check if the access node is alive and healthy.
   *
   * @generated from rpc execution.ExecutionAPI.Ping
   */
  ping: {
    methodKind: "unary"
    input: typeof PingRequestSchema
    output: typeof PingResponseSchema
  }
  /**
   * GetAccountAtBlockID gets an account by address at the given block ID
   *
   * @generated from rpc execution.ExecutionAPI.GetAccountAtBlockID
   */
  getAccountAtBlockID: {
    methodKind: "unary"
    input: typeof GetAccountAtBlockIDRequestSchema
    output: typeof GetAccountAtBlockIDResponseSchema
  }
  /**
   * ExecuteScriptAtBlockID executes a ready-only Cadence script against the
   * execution state at the block with the given ID.
   *
   * @generated from rpc execution.ExecutionAPI.ExecuteScriptAtBlockID
   */
  executeScriptAtBlockID: {
    methodKind: "unary"
    input: typeof ExecuteScriptAtBlockIDRequestSchema
    output: typeof ExecuteScriptAtBlockIDResponseSchema
  }
  /**
   * GetEventsForBlockIDs retrieves events for all the specified block IDs that
   * have the given type
   *
   * @generated from rpc execution.ExecutionAPI.GetEventsForBlockIDs
   */
  getEventsForBlockIDs: {
    methodKind: "unary"
    input: typeof GetEventsForBlockIDsRequestSchema
    output: typeof GetEventsForBlockIDsResponseSchema
  }
  /**
   * GetTransactionResult gets the result of a transaction.
   *
   * @generated from rpc execution.ExecutionAPI.GetTransactionResult
   */
  getTransactionResult: {
    methodKind: "unary"
    input: typeof GetTransactionResultRequestSchema
    output: typeof GetTransactionResultResponseSchema
  }
}> = /*@__PURE__*/ serviceDesc(file_flow_legacy_execution_execution, 0)
